processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 56-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-83:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  170,
                                  239,
                                  81,
                                  8,
                                  247,
                                  132,
                                  129,
                                  179,
                                  213,
                                  231,
                                  30,
                                  178,
                                  254,
                                  161,
                                  228,
                                  107,
                                  201,
                                  215,
                                  96,
                                  130,
                                  43,
                                  224,
                                  152,
                                  48,
                                  228,
                                  0,
                                  230,
                                  181,
                                  189,
                                  210,
                                  21,
                                  226
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xaaef5108f78481b3d5e71eb2fea1e46bc9d760822be09830e400e6b5bdd215e2",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x6f323203883c515553fd70a5e66dbd1c84877d09c147329d357efba52157ff99::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  204,
                                  75,
                                  172,
                                  137,
                                  122,
                                  184,
                                  50,
                                  138,
                                  0,
                                  137,
                                  81,
                                  162,
                                  107,
                                  135,
                                  222,
                                  134,
                                  105,
                                  187,
                                  26,
                                  210,
                                  19,
                                  44,
                                  188,
                                  128,
                                  215,
                                  25,
                                  40,
                                  221,
                                  8,
                                  144,
                                  213,
                                  142
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  204,
                                  75,
                                  172,
                                  137,
                                  122,
                                  184,
                                  50,
                                  138,
                                  0,
                                  137,
                                  81,
                                  162,
                                  107,
                                  135,
                                  222,
                                  134,
                                  105,
                                  187,
                                  26,
                                  210,
                                  19,
                                  44,
                                  188,
                                  128,
                                  215,
                                  25,
                                  40,
                                  221,
                                  8,
                                  144,
                                  213,
                                  142
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      204,
                                      75,
                                      172,
                                      137,
                                      122,
                                      184,
                                      50,
                                      138,
                                      0,
                                      137,
                                      81,
                                      162,
                                      107,
                                      135,
                                      222,
                                      134,
                                      105,
                                      187,
                                      26,
                                      210,
                                      19,
                                      44,
                                      188,
                                      128,
                                      215,
                                      25,
                                      40,
                                      221,
                                      8,
                                      144,
                                      213,
                                      142
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xcc4bac897ab8328a008951a26b87de8669bb1ad2132cbc80d71928dd0890d58e",
                          "f0": "0xcc4bac897ab8328a008951a26b87de8669bb1ad2132cbc80d71928dd0890d58e",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xcc4bac897ab8328a008951a26b87de8669bb1ad2132cbc80d71928dd0890d58e"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
